### ISSUE TITLE
After repushing a pdf, it endlessly loads on opening

### ISSUE THREAD

**Issue by jackjackk** [reHackable/scripts#13]
I have been using repush.sh for a while and really love it. Unfortunately, I guess after some recent major updates by reMarkable, the script doesn't work any more, at least for me. I could identify a problem with `grep` being called via ssh, which now gives an error:
```
unrecognized option '--color=auto'
```
which is easily solvable by replacing the remote `grep` instances in the script with `/bin/grep`. After fixing that, I can upload a pdf and see it on the "My Files" page, and redownload it from the WebUI, but cannot open it on the tablet. If I do so, it endlessly shows the 3 dots of loading. I think it gets stuck somewhere in either 1) generating thumbnails or 2) page information. For example, the content file shows sth like
```
    "pageCount": 0,
    "pages": [
    ],
```
 I tried with a couple of different pdfs and the behavior is the same.

I would really love to solve this issue as I find this script the best way to interact with my reMarkable.
Thanks

**Comment by CTXz** [comment]
Hey @jackjackk ,

First off, thanks for the positive feedback!

My device is still running software version `1.6.0.6`, and as you may have already heard, the reMarkable 1.7 update is currently on hold due to a "potential issue" that has discovered by the rM team. In order to assist you, I would require access to the software version.

I would highly appreciate if someone with the latest software version would be willing to lend me a hand and help me test any changes made to rePush. If you see interest in doing so, please message me on the [reMarkable discord sever](https://discordapp.com/invite/JSSGnFY)!

**Comment by CTXz** [comment]
Fixed in https://github.com/reHackable/scripts/commit/06620992ea8ea5e8866a894237287d5ae78a3b5c

Thanks for offering me a hand! Sorry for taking a while, although we mostly already fixed this issue a while back ago I wanted to get my own hands on it before pushing any changes.
