### ISSUE TITLE
repush doesn't copy files with spaces

### ISSUE THREAD

**Issue by vinipsmaker** [reHackable/scripts#16]

**Comment by CTXz** [comment]
This issue has absolutely no information to it. No version number, no description, not even a copy of the command output... Is it really so difficult to provide at least some information?

Which version are you running? Please output the result of `./repush.sh -v`

**Comment by Profpatsch** [comment]
… but does it run https://github.com/koalaman/shellcheck?

**Comment by vinipsmaker** [comment]
> This issue has absolutely no information to it. No version number, no description

Commit 8b963c6f88cd122707e46a21eeffaf46da79c15e

> not even a copy of the command output

```
$ repush.sh foo\ bar.epub
repush: No such file or directory: foo
zsh: exit 255   repush.sh
```

> Is it really so difficult to provide at least some information?

Usually I write more detailed bug reports, but I thought no one would care, so it was more of a reminder until I have some free time to take a look at the script and fix it.

**Comment by CTXz** [comment]
The commit that you've linked is related to webui_invicibility, further, you have still not provided the output of `./repush.sh -v`.

If you're planning to patch something yourself, please submit a PR instead of a issue with absolutely no content. If you need to  create a reminder, please use different tools than Github's issue system. How about google keep, or perhaps even a pen and some sticky notes. 

Also, what exactly makes you think no one would care? A quick glance at the commits and closed issues would easily tell you that I am still actively maintaining this repository.

Okay, now all of that put aside, you're probably running a older version of repush. This issue has recently been patched in [this commit](https://github.com/reHackable/scripts/commit/f619aaae4fbb01461607d4111cf8003017686ae9) about 8 days ago. If your repush version is lower than 4.1, (check using `repush.sh -v`), then download the latest version of repush.

**Comment by vinipsmaker** [comment]
>The commit that you've linked is related to webui_invicibility

The commit I've linked was the version of my local tree/clone of the repo.

>Okay, now all of that put aside, you're probably running a older version of repush. This issue has recently been patched in [this commit](https://github.com/reHackable/scripts/commit/f619aaae4fbb01461607d4111cf8003017686ae9) about 8 days ago.

That fixed. Thank you.
