### ISSUE TITLE
Saving my password?

### ISSUE THREAD

**Issue by 1094** [reHackable/scripts#17]
First, I want to say I am so grateful for these scripts! Thank you for creating them and sharing them with the world.

Second, the question: Is it possible to save my rM's password to the script? I have to re-enter it for every file I push, which can get a bit annoying when pushing more than three PDFs at a time.

Thanks for your time.

**Comment by CTXz** [comment]
Thanks for the kind feedback!

Yes, you can by setting up an ssh key. See the "Setting up ssh-keys" section on the [reMarkable wiki SSH page](https://remarkablewiki.com/tech/ssh).

I've also added this question to the FAQ section for the repush and repull scripts now.

**Comment by 1094** [comment]
So, I can't add a line or variable to the script itself, it needs to be a SSH key?
Okay. Thanks.

**Comment by CTXz** [comment]
Technically you could, but such an unorthodox approach could come with all kinds of security concerns in my opinion.

[And this isn't just my opinion](https://serverfault.com/questions/241588/how-to-automate-ssh-login-with-password)

It'd probably require you to use [sshpass](https://linux.die.net/man/1/sshpass) since there's no official option to pass a SSH password from the command line.
